# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20180912_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='longtitue',
            new_name='longtitude',
        ),
    ]
