# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20180913_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='category',
        ),
        migrations.AddField(
            model_name='user',
            name='category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
