# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_expertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertise',
            name='category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
