# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
