# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-28 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20180927_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.FloatField(blank=True, default='5.0', max_length=255, null=True),
        ),
    ]
