# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-28 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_auto_20180928_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, max_length=5000, null=True)),
                ('from_id', models.IntegerField(blank=True, null=True)),
                ('to_id', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, default='1', null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('replied_date', models.DateTimeField()),
            ],
        ),
    ]
