# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-28 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='replied_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
