# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-28 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20180928_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
