# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-28 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_auto_20180928_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='from_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='to_id',
        ),
    ]
