# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-29 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_auto_20180928_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='replied_message',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
