# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 11:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_message_replied_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
