# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 12:11
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_auto_20180930_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, max_length=5000, null=True)),
                ('status', models.IntegerField(blank=True, default='1', null=True)),
                ('rating', models.IntegerField(blank=True, default='5', null=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
