# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-03 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
