# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-03 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_user_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=b''),
        ),
    ]
